name: Deploy to Private EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: SSH and Deploy to EC2 via Bastion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for context only)
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Bastion Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts || true

      - name: SSH into Private EC2 and Pull Repo
        run: |
          ssh -o ProxyCommand="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.BASTION_HOST }} -W %h:%p" \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ubuntu@${{ secrets.PRIVATE_HOST }} \
              'cd /var/www/html/phpDemo && git pull origin main || (rm -rf /var/www/html/phpDemo && git clone https://github.com/<your-username>/<your-repo>.git /var/www/html/phpDemo)'
