name: Deploy to Private EC2 via Bastion

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.PRIVATE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via Bastion
      run: |
        ssh -o ProxyJump=ubuntu@${{ secrets.BASTION_HOST }} ubuntu@${{ secrets.PRIVATE_HOST }} << 'EOF'
          cd /var/www/html/phpDemo
          git pull origin main
          sudo systemctl restart apache2
        EOF
