name: Deploy to Private EC2

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Bastion to known_hosts
        run: ssh-keyscan -H ${{ secrets.BASTION_PUBLIC_IP }} >> ~/.ssh/known_hosts
      
      - name: Add Private EC2 to known_hosts via Bastion
        run: |
          ssh -o ProxyCommand="ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_PUBLIC_IP }} -W %h:%p" \
              ubuntu@${{ secrets.APP_PRIVATE_IP }} "echo Host verified" || true
      
      - name: Pull latest code into EC2 via Bastion
        run: |
          ssh -o ProxyCommand="ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_PUBLIC_IP }} -W %h:%p" \
              ubuntu@${{ secrets.APP_PRIVATE_IP }} << 'EOF'
            if [ -d /var/www/html/phpDemo/.git ]; then
              sudo git -C /var/www/html/phpDemo pull origin main
            else
              sudo git clone https://github.com/<your-username>/<your-repo>.git /var/www/html/phpDemo
            fi
          EOF
